version: '3.8'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb+srv://Admin:Admin123@cluster0.of8dm.mongodb.net/authDB?retryWrites=true&w=majority
      - JWT_EXPIRES_IN=1d
      - JWT_SECRET=7fkd93Kejfskdjfh3947fKJDF983jdslf!@#$$%@3jkdfhsdfh9384
      - NODE_ENV=development
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000
      - GOOGLE_CLIENT_ID=335033738118-c5eiaqjoietnjncppvibs6k1vrnlncdv.apps.googleusercontent.com

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb+srv://Admin:Admin123@cluster0.of8dm.mongodb.net/restaurantDB?retryWrites=true&w=majority
      # <-- use service names here, not localhost
      - ORDER_SERVICE_URL=http://order-service:3003/api/orders
      - AUTH_SERVICE_URL=http://auth-service:3001/api/auth
      - JWT_EXPIRES_IN=1d
      - JWT_SECRET=7fkd93Kejfskdjfh3947fKJDF983jdslf!@#$$%@3jkdfhsdfh9384

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URI=mongodb+srv://Admin:Admin123@cluster0.of8dm.mongodb.net/orderDB?retryWrites=true&w=majority
      - VITE_GOOGLE_MAPS_API_KEY=AIzaSyAEKepFgGssHp94zRkRIEZUttqfXDTpRUE
      - PAYHERE_SECRET=MTYzMjA5Mzc2NjM0NjA2OTA4NjAxMzIwODEwMzU5NDE3OTA0NzgyMw==
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000
      - NODE_ENV=development
      # <-- service-name URLs here too
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
      - PAYMENT_SERVICE_URL=http://payment-service:3005
      - AUTH_SERVICE_URL=http://auth-service:3001/api/auth

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "3009:3009"
    environment:
      - PORT=3009
      - MONGO_URI=mongodb+srv://Admin:Admin123@cluster0.of8dm.mongodb.net/deliveryDB?retryWrites=true&w=majority
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000
      - NODE_ENV=development
      # <-- and here
      - ORDER_SERVICE_URL=http://order-service:3003/api/orders
      - AUTH_SERVICE_URL=http://auth-service:3001/api/auth
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - PAYHERE_MERCHANT_ID=1230207
      - PAYHERE_MERCHANT_SECRET=MTYzMjA5Mzc2NjM0NjA2OTA4NjAxMzIwODEwMzU5NDE3OTA0NzgyMw==

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - restaurant-service
      - order-service
      - delivery-service
      - notification-service
      - payment-service
    environment:
      - VITE_AUTH_SERVICE_URL=http://localhost:3001/api/auth
      - VITE_RESTAURANT_SERVICE_URL=http://localhost:3002/api
      - VITE_ORDER_SERVICE_URL=http://localhost:3003/api/orders
      - VITE_DRIVER_SERVICE_URL=http://localhost:3009/api/driver
      - VITE_GOOGLE_MAPS_API_KEY=AIzaSyD6_oU88ERy42sI2ztVRdfm0UN5OKXoJFs
      - VITE_PAYMENT_SERVICE_URL=http://localhost:3005
      - VITE_GOOGLE_CLIENT_ID=335033738118-c5eiaqjoietnjncppvibs6k1vrnlncdv.apps.googleusercontent.com
